## Python Sudoku Solver
### currently this code solves by brute-force
### good for easy and medium puzzles. hard puzzles takes a long time to converge.
### to add additional check steps prior to brute-force

In [16]:

import numpy as np

In [17]:
grid = [[0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0]]

In [18]:
grid = [[0,5,0,0,1,0,0,0,0],
        [3,4,0,5,2,0,0,0,7],
        [7,1,0,0,8,0,6,0,0],
        [1,0,0,2,6,0,4,0,0],
        [4,6,7,0,0,0,2,1,8],
        [0,0,5,0,4,7,0,0,9],
        [0,0,6,0,9,0,0,8,2],
        [2,0,0,0,5,3,0,4,6],
        [0,0,0,0,7,0,0,3,0]]

In [19]:
print(np.matrix(grid))

[[0 5 0 0 1 0 0 0 0]
 [3 4 0 5 2 0 0 0 7]
 [7 1 0 0 8 0 6 0 0]
 [1 0 0 2 6 0 4 0 0]
 [4 6 7 0 0 0 2 1 8]
 [0 0 5 0 4 7 0 0 9]
 [0 0 6 0 9 0 0 8 2]
 [2 0 0 0 5 3 0 4 6]
 [0 0 0 0 7 0 0 3 0]]


In [23]:
def check(y, x, n):
    '''
    This function checks for 3 primary conditions
    '''
    global grid
    for i in range (0,9):
        if grid[y][i]==n:
            return False
    for i in range (0, 9):
        if grid[i][x]==n:
            return False
    x1 = (x//3)*3
    y1 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y1+i][x1+i] == n:
                return False
    return True

In [38]:
def solve():
    global grid
    '''
    This is a recursive function, that enters a candidate in vacant position
    if conditions is 'check function' is satisfied
    '''
    i=0
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1,10):
                    if check(y, x, n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    i+=1
    print(f"trial {i}")
    print(np.matrix(grid))
    return grid

In [39]:
solve()

trial 1
[[6 5 9 7 1 4 8 2 3]
 [3 4 8 5 2 6 1 9 7]
 [7 1 2 3 8 9 6 5 4]
 [1 9 3 2 6 8 4 7 5]
 [4 6 7 9 3 5 2 1 8]
 [8 2 5 1 4 7 3 6 9]
 [5 3 6 4 9 1 7 8 2]
 [2 7 1 8 5 3 9 4 6]
 [9 8 4 6 7 2 5 3 1]]
